# ~/.config/hypr/hyprlock.conf

background {
    path = ~/.config/hypr/themes/purple/hypr/hyprlock/wall.jpg
    blur_passes = 2
    blur_size = 4
}

general {
    hide_cursor = true
    grace = 0
}

# ساعت
label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"

    color = rgba(255,255,255,0.95)

    font_family = Inter Bold
    font_size = 96

    position = 0, 220
    halign = center
    valign = center
}

# تاریخ
label {
    text = cmd[update:60000] echo "$(date +'%A, %-d %B')"

    color = rgba(230,230,230,0.9)

    font_family = Inter
    font_size = 26

    position = 0, 145
    halign = center
    valign = center
}

image {
    path = ~/.config/hypr/themes/purple/hypr/hyprlock/Toex.jpg

    size = 110

    rounding = -1

    position = 0, 35
    halign = center
    valign = center
}

label {
    text = Hi, Toex

    color = rgba(255,255,255,0.95)

    font_family = Inter
    font_size = 28

    position = 0, -55
    halign = center
    valign = center
}

input-field {
    size = 320, 55

    outline_thickness = 0

    dots_center = true
    fade_on_empty = false

    placeholder_text = Enter Pass

    font_family = Inter
    font_size = 18

    inner_color = rgba(255,255,255,0.15)
    outer_color = rgba(255,255,255,0.0)
    font_color = rgba(255,255,255,0.95)

    rounding = 18

    position = 0, -135
    halign = center
    valign = center
}
animations {
    enabled = true

    bezier = easeOutQuart, 0.25, 1, 0.5, 1

    animation = fadeIn, 1, 6, easeOutQuart
    animation = fadeOut, 1, 6, easeOutQuart

    animation = inputFieldFade, 1, 5, easeOutQuart
    animation = inputFieldDots, 1, 5, easeOutQuart
    animation = inputFieldColors, 1, 4, easeOutQuart
}
