splash = false
ipc = true

wallpaper {
    monitor = eDP-1
    path = /home/toex/Pictures/wall/1.jpg
    fit_mode = fill
    timeout = 30
}
wallpaper {
    monitor = eDP-1
    path = /home/toex/Pictures/wall/gavazn.jpg
    fit_mode = fill
}
