[open]
rules = [
  { mime = "video/*", use = "video" },
  { mime = "audio/*", use = "audio" },
  { mime = "image/*", use = "image" }
]

[opener]
video = [
  { run = 'mpv "$@"', orphan = true}]
audio = [
  { run = 'mpv "$@"', orphan = true }]
image = [
  { run = 'feh "$@"', orphan = true }]

